const Products = [{ "id": "1", "name": "iphone 13 pro", "price": "1000", "description": "product descrptions", "image": "/image/product/10.png", "amount": "0", "rate": 5.0, "color": "red", "size": "large", "brand": "Apple", "manufactureDate": "2022" },
{ "id": "2", "name": "apple TV", "price": "340", "description": "product descrptions", "image": "/image/product/7.png", "amount": "0", "rate": 4.0, "color": "yellow", "size": "large", "brand": "Apple", "manufactureDate": "2022" },
{ "id": "3", "name": "macbook pro", "price": "700", "description": "product descrptions", "image": "/image/product/3.png", "amount": "0", "rate": 4.0, "color": "red", "size": "large", "brand": "Apple", "manufactureDate": "2021" },
{ "id": "4", "name": "iphone 13", "price": "999", "description": "product descrptions", "image": "/image/product/4.png", "amount": "0", "rate": 4.0, "color": "red", "size": "medium", "brand": "Apple", "manufactureDate": "2022" },
{ "id": "5", "name": "MacBook 14 pro", "price": "500", "description": "product descrptions", "image": "/image/product/5.png", "amount": "0", "rate": 5.0, "color": "red", "size": "large", "brand": "Apple", "manufactureDate": "2022" },
{ "id": "6", "name": "Keyboard max", "price": "50", "description": "product descrptions", "image": "/image/product/6.png", "amount": "0", "rate": 3.0, "color": "black", "size": "large", "brand": "HP", "manufactureDate": "2022" },
{ "id": "7", "name": "Netflix TV", "price": "1000", "description": "product descrptions", "image": "/image/product/2.png", "amount": "0", "rate": 4.0, "color": "black", "size": "large", "brand": "Samsung", "manufactureDate": "2020" },
{ "id": "8", "name": "Apple watch 14 pro", "price": "600", "description": "product descrptions", "image": "/image/product/8.png", "amount": "0", "rate": 4.0, "color": "red", "size": "large", "brand": "Apple", "manufactureDate": "2022" },
{ "id": "9", "name": "iphone 13 mini", "price": "100", "description": "product descrptions", "image": "/image/product/9.png", "amount": "0", "rate": 5.0, "color": "blue", "size": "medium", "brand": "Apple", "manufactureDate": "2022" },
{ "id": "10", "name": "Samsung A71", "price": "20", "description": "product descrptions", "image": "/image/product/11.png", "amount": "0", "rate": 4.0, "color": "silver", "size": "large", "brand": "Samsung", "manufactureDate": "2020" }]

export default Products